[tool.poetry]
name = "vprikol-api-python"
version = "1.8.2"
description = ""
authors = ["Alex <alexank1111@gmail.com>"]
readme = "README.md"
packages = [{include = "vprikol_api"}]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.10.7"
aiohttp = "^3.8.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
